---
weight_dir: checkpoints/urban_synth2cs

common:
  unpin: false
  batch_size: 1
  num_loaders: 14
  log_interval: 50
  seed: 1  

train:
  max_epochs: -1
  max_iterations: 1000000
  save_epochs: -1
  save_iterations: 10000
  name_save: synth2cs
  shuffle_train: true
  val_interval: 10000
   
test:
  shuffle_test: false

real_dataset:
  name: Cityscapes
  filelist: /home/sanjitk/repos/PhotorealismEnhancement/data/real/cityscapes_munich_resized/cityscapes_munich_resized_files.csv

fake_dataset: 
  name: AppliedSynthetic
  train_filelist: /home/sanjitk/repos/PhotorealismEnhancement/data/synthetic/urban_synth/urban_synth_files.csv
  val_filelist: /home/sanjitk/repos/PhotorealismEnhancement/data/synthetic/urban_synth/urban_synth_files.csv
  test_filelist: /home/sanjitk/repos/PhotorealismEnhancement/data/synthetic/urban_synth/urban_synth_files.csv
  sampling: 
    type: 'matching'
    matched_crop_path: /home/sanjitk/repos/PhotorealismEnhancement/data/synthetic/urban_synth/knn_matches_filtered.csv
    crop_weight_path: /home/sanjitk/repos/PhotorealismEnhancement/data/synthetic/urban_synth/crop_weights.npz


generator:
  type: hr_new
  config:
    encoder_type: ENCODER
    stem_norm: group
    num_stages: 6
    other_norm: group
    gbuffer_norm: RAC
    gbuffer_encoder_norm: residual2
    num_gbuffer_layers: 3
  optimizer:
    type: adam
    learning_rate: 0.0001
    adam_beta: 0.9
    adam_beta2: 0.999
    clip_gradient_norm: 1000
  scheduler:
    type: 'step'
    step: 100000
    gamma: 0.5
    
discriminator:
  type: ppde
  run_always: false
  config:
    norm: group
    num_layers: 4
    max_dim: 256
  optimizer:
    type: adam
    learning_rate: 0.0001 
    adam_beta: 0.9
    adam_beta2: 0.999
    clip_gradient_norm: 1000
  scheduler:
    type: 'step'
    step: 1000000
    gamma: 0.5
    
objectives:
  gan: ls
  perceptual:
    type: 'lpips_vgg'
    weight: 1
  reg:
    weight: 0.03
...
